/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flyscale_alertor_jni_NativeHelper */

#ifndef _Included_com_flyscale_alertor_jni_NativeHelper
#define _Included_com_flyscale_alertor_jni_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flyscale_alertor_jni_NativeHelper
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_alertor_jni_NativeHelper_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_flyscale_alertor_jni_NativeHelper
 * Method:    desEncrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_flyscale_alertor_jni_NativeHelper_desEncrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_flyscale_alertor_jni_NativeHelper
 * Method:    desDecrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_flyscale_alertor_jni_NativeHelper_desDecrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
